package eo;

import oracle.jbo.ApplicationModule;
import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 27 21:35:23 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TbClienteImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        IdCliente {
            public Object get(TbClienteImpl obj) {
                return obj.getIdCliente();
            }

            public void put(TbClienteImpl obj, Object value) {
                obj.setIdCliente((Number)value);
            }
        }
        ,
        Nome {
            public Object get(TbClienteImpl obj) {
                return obj.getNome();
            }

            public void put(TbClienteImpl obj, Object value) {
                obj.setNome((String)value);
            }
        }
        ,
        CpfCnpj {
            public Object get(TbClienteImpl obj) {
                return obj.getCpfCnpj();
            }

            public void put(TbClienteImpl obj, Object value) {
                obj.setCpfCnpj((String)value);
            }
        }
        ,
        Telefone {
            public Object get(TbClienteImpl obj) {
                return obj.getTelefone();
            }

            public void put(TbClienteImpl obj, Object value) {
                obj.setTelefone((String)value);
            }
        }
        ,
        Email {
            public Object get(TbClienteImpl obj) {
                return obj.getEmail();
            }

            public void put(TbClienteImpl obj, Object value) {
                obj.setEmail((String)value);
            }
        }
        ,
        Endereco {
            public Object get(TbClienteImpl obj) {
                return obj.getEndereco();
            }

            public void put(TbClienteImpl obj, Object value) {
                obj.setEndereco((String)value);
            }
        }
        ,
        TbOrdemDeServico {
            public Object get(TbClienteImpl obj) {
                return obj.getTbOrdemDeServico();
            }

            public void put(TbClienteImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(TbClienteImpl object);

        public abstract void put(TbClienteImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDCLIENTE = AttributesEnum.IdCliente.index();
    public static final int NOME = AttributesEnum.Nome.index();
    public static final int CPFCNPJ = AttributesEnum.CpfCnpj.index();
    public static final int TELEFONE = AttributesEnum.Telefone.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int ENDERECO = AttributesEnum.Endereco.index();
    public static final int TBORDEMDESERVICO = AttributesEnum.TbOrdemDeServico.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TbClienteImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("eo.TbCliente");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for IdCliente, using the alias name IdCliente.
     * @return the IdCliente
     */
    public Number getIdCliente() {
        return (Number)getAttributeInternal(IDCLIENTE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdCliente.
     * @param value value to set the IdCliente
     */
    public void setIdCliente(Number value) {
        setAttributeInternal(IDCLIENTE, value);
    }

    /**
     * Gets the attribute value for Nome, using the alias name Nome.
     * @return the Nome
     */
    public String getNome() {
        return (String)getAttributeInternal(NOME);
    }

    /**
     * Sets <code>value</code> as the attribute value for Nome.
     * @param value value to set the Nome
     */
    public void setNome(String value) {
        setAttributeInternal(NOME, value);
    }

    /**
     * Gets the attribute value for CpfCnpj, using the alias name CpfCnpj.
     * @return the CpfCnpj
     */
    public String getCpfCnpj() {
        return (String)getAttributeInternal(CPFCNPJ);
    }

    /**
     * Sets <code>value</code> as the attribute value for CpfCnpj.
     * @param value value to set the CpfCnpj
     */
    public void setCpfCnpj(String value) {
        setAttributeInternal(CPFCNPJ, value);
    }

    /**
     * Gets the attribute value for Telefone, using the alias name Telefone.
     * @return the Telefone
     */
    public String getTelefone() {
        return (String)getAttributeInternal(TELEFONE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Telefone.
     * @param value value to set the Telefone
     */
    public void setTelefone(String value) {
        setAttributeInternal(TELEFONE, value);
    }

    /**
     * Gets the attribute value for Email, using the alias name Email.
     * @return the Email
     */
    public String getEmail() {
        return (String)getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Email.
     * @param value value to set the Email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for Endereco, using the alias name Endereco.
     * @return the Endereco
     */
    public String getEndereco() {
        return (String)getAttributeInternal(ENDERECO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Endereco.
     * @param value value to set the Endereco
     */
    public void setEndereco(String value) {
        setAttributeInternal(ENDERECO, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTbOrdemDeServico() {
        return (RowIterator)getAttributeInternal(TBORDEMDESERVICO);
    }


    /**
     * @param idCliente key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number idCliente) {
        return new Key(new Object[]{idCliente});
    }

    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        //Sequence
        ApplicationModule root = getDBTransaction().getRootApplicationModule();
        DBSequence seqid = new DBSequence("SEQ_TB_CLIENTE", root);
        setIdCliente(seqid.getSequenceNumber());
    }

}
