package eo;

import oracle.jbo.ApplicationModule;
import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 15 00:04:54 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TbMotoristaImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        IdMotorista {
            public Object get(TbMotoristaImpl obj) {
                return obj.getIdMotorista();
            }

            public void put(TbMotoristaImpl obj, Object value) {
                obj.setIdMotorista((Number)value);
            }
        }
        ,
        Nome {
            public Object get(TbMotoristaImpl obj) {
                return obj.getNome();
            }

            public void put(TbMotoristaImpl obj, Object value) {
                obj.setNome((String)value);
            }
        }
        ,
        Cpf {
            public Object get(TbMotoristaImpl obj) {
                return obj.getCpf();
            }

            public void put(TbMotoristaImpl obj, Object value) {
                obj.setCpf((String)value);
            }
        }
        ,
        Telefone {
            public Object get(TbMotoristaImpl obj) {
                return obj.getTelefone();
            }

            public void put(TbMotoristaImpl obj, Object value) {
                obj.setTelefone((String)value);
            }
        }
        ,
        Email {
            public Object get(TbMotoristaImpl obj) {
                return obj.getEmail();
            }

            public void put(TbMotoristaImpl obj, Object value) {
                obj.setEmail((String)value);
            }
        }
        ,
        Endereco {
            public Object get(TbMotoristaImpl obj) {
                return obj.getEndereco();
            }

            public void put(TbMotoristaImpl obj, Object value) {
                obj.setEndereco((String)value);
            }
        }
        ,
        FkCatHab {
            public Object get(TbMotoristaImpl obj) {
                return obj.getFkCatHab();
            }

            public void put(TbMotoristaImpl obj, Object value) {
                obj.setFkCatHab((Number)value);
            }
        }
        ,
        TbCatHab {
            public Object get(TbMotoristaImpl obj) {
                return obj.getTbCatHab();
            }

            public void put(TbMotoristaImpl obj, Object value) {
                obj.setTbCatHab((EntityImpl)value);
            }
        }
        ,
        TbOrdemDeServico {
            public Object get(TbMotoristaImpl obj) {
                return obj.getTbOrdemDeServico();
            }

            public void put(TbMotoristaImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(TbMotoristaImpl object);

        public abstract void put(TbMotoristaImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDMOTORISTA = AttributesEnum.IdMotorista.index();
    public static final int NOME = AttributesEnum.Nome.index();
    public static final int CPF = AttributesEnum.Cpf.index();
    public static final int TELEFONE = AttributesEnum.Telefone.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int ENDERECO = AttributesEnum.Endereco.index();
    public static final int FKCATHAB = AttributesEnum.FkCatHab.index();
    public static final int TBCATHAB = AttributesEnum.TbCatHab.index();
    public static final int TBORDEMDESERVICO = AttributesEnum.TbOrdemDeServico.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TbMotoristaImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("eo.TbMotorista");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for IdMotorista, using the alias name IdMotorista.
     * @return the IdMotorista
     */
    public Number getIdMotorista() {
        return (Number)getAttributeInternal(IDMOTORISTA);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdMotorista.
     * @param value value to set the IdMotorista
     */
    public void setIdMotorista(Number value) {
        setAttributeInternal(IDMOTORISTA, value);
    }

    /**
     * Gets the attribute value for Nome, using the alias name Nome.
     * @return the Nome
     */
    public String getNome() {
        return (String)getAttributeInternal(NOME);
    }

    /**
     * Sets <code>value</code> as the attribute value for Nome.
     * @param value value to set the Nome
     */
    public void setNome(String value) {
        setAttributeInternal(NOME, value);
    }

    /**
     * Gets the attribute value for Cpf, using the alias name Cpf.
     * @return the Cpf
     */
    public String getCpf() {
        return (String)getAttributeInternal(CPF);
    }

    /**
     * Sets <code>value</code> as the attribute value for Cpf.
     * @param value value to set the Cpf
     */
    public void setCpf(String value) {
        setAttributeInternal(CPF, value);
    }

    /**
     * Gets the attribute value for Telefone, using the alias name Telefone.
     * @return the Telefone
     */
    public String getTelefone() {
        return (String)getAttributeInternal(TELEFONE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Telefone.
     * @param value value to set the Telefone
     */
    public void setTelefone(String value) {
        setAttributeInternal(TELEFONE, value);
    }

    /**
     * Gets the attribute value for Email, using the alias name Email.
     * @return the Email
     */
    public String getEmail() {
        return (String)getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Email.
     * @param value value to set the Email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for Endereco, using the alias name Endereco.
     * @return the Endereco
     */
    public String getEndereco() {
        return (String)getAttributeInternal(ENDERECO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Endereco.
     * @param value value to set the Endereco
     */
    public void setEndereco(String value) {
        setAttributeInternal(ENDERECO, value);
    }

    /**
     * Gets the attribute value for FkCatHab, using the alias name FkCatHab.
     * @return the FkCatHab
     */
    public Number getFkCatHab() {
        return (Number)getAttributeInternal(FKCATHAB);
    }

    /**
     * Sets <code>value</code> as the attribute value for FkCatHab.
     * @param value value to set the FkCatHab
     */
    public void setFkCatHab(Number value) {
        setAttributeInternal(FKCATHAB, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getTbCatHab() {
        return (EntityImpl)getAttributeInternal(TBCATHAB);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setTbCatHab(EntityImpl value) {
        setAttributeInternal(TBCATHAB, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTbOrdemDeServico() {
        return (RowIterator)getAttributeInternal(TBORDEMDESERVICO);
    }


    /**
     * @param idMotorista key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number idMotorista) {
        return new Key(new Object[]{idMotorista});
    }

    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        //Sequence
        ApplicationModule root = getDBTransaction().getRootApplicationModule();
        DBSequence seqid = new DBSequence("SEQ_TB_MOTORISTA", root);
        setIdMotorista(seqid.getSequenceNumber());
    }
}
