package am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Apr 19 22:27:46 BRT 2014
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    int autenticarUsuario(String userid, String pass);
}
