package am;

import am.common.AppModule;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;

import vo.TbFuncionarioViewImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Apr 19 22:11:58 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for TbCatHabView1.
     * @return TbCatHabView1
     */
    public ViewObjectImpl getTbCatHabView1() {
        return (ViewObjectImpl)findViewObject("TbCatHabView1");
    }

    /**
     * Container's getter for TbClienteView1.
     * @return TbClienteView1
     */
    public ViewObjectImpl getTbClienteView1() {
        return (ViewObjectImpl)findViewObject("TbClienteView1");
    }

    /**
     * Container's getter for TbDiariaView1.
     * @return TbDiariaView1
     */
    public ViewObjectImpl getTbDiariaView1() {
        return (ViewObjectImpl)findViewObject("TbDiariaView1");
    }

    /**
     * Container's getter for TbFranquiaView1.
     * @return TbFranquiaView1
     */
    public ViewObjectImpl getTbFranquiaView1() {
        return (ViewObjectImpl)findViewObject("TbFranquiaView1");
    }

    /**
     * Container's getter for TbFuncionarioView1.
     * @return TbFuncionarioView1
     */
    public ViewObjectImpl getTbFuncionarioView1() {
        return (ViewObjectImpl)findViewObject("TbFuncionarioView1");
    }

    /**
     * Container's getter for TbMotoristaView1.
     * @return TbMotoristaView1
     */
    public ViewObjectImpl getTbMotoristaView1() {
        return (ViewObjectImpl)findViewObject("TbMotoristaView1");
    }

    /**
     * Container's getter for TbOrdemDeServicoView1.
     * @return TbOrdemDeServicoView1
     */
    public ViewObjectImpl getTbOrdemDeServicoView1() {
        return (ViewObjectImpl)findViewObject("TbOrdemDeServicoView1");
    }

    /**
     * Container's getter for TbPerfilView1.
     * @return TbPerfilView1
     */
    public ViewObjectImpl getTbPerfilView1() {
        return (ViewObjectImpl)findViewObject("TbPerfilView1");
    }

    /**
     * Container's getter for TbDiariaView2.
     * @return TbDiariaView2
     */
    public ViewObjectImpl getTbDiariaView2() {
        return (ViewObjectImpl)findViewObject("TbDiariaView2");
    }

    /**
     * Container's getter for TbMotoristaView2.
     * @return TbMotoristaView2
     */
    public ViewObjectImpl getTbMotoristaView2() {
        return (ViewObjectImpl)findViewObject("TbMotoristaView2");
    }

    /**
     * Container's getter for TbDiariaView3.
     * @return TbDiariaView3
     */
    public ViewObjectImpl getTbDiariaView3() {
        return (ViewObjectImpl)findViewObject("TbDiariaView3");
    }

    /**
     * Container's getter for TbOrdemDeServicoView2.
     * @return TbOrdemDeServicoView2
     */
    public ViewObjectImpl getTbOrdemDeServicoView2() {
        return (ViewObjectImpl)findViewObject("TbOrdemDeServicoView2");
    }

    /**
     * Container's getter for TbOrdemDeServicoView3.
     * @return TbOrdemDeServicoView3
     */
    public ViewObjectImpl getTbOrdemDeServicoView3() {
        return (ViewObjectImpl)findViewObject("TbOrdemDeServicoView3");
    }

    /**
     * Container's getter for TbOrdemDeServicoView4.
     * @return TbOrdemDeServicoView4
     */
    public ViewObjectImpl getTbOrdemDeServicoView4() {
        return (ViewObjectImpl)findViewObject("TbOrdemDeServicoView4");
    }

    /**
     * Container's getter for TbFuncionarioView2.
     * @return TbFuncionarioView2
     */
    public ViewObjectImpl getTbFuncionarioView2() {
        return (ViewObjectImpl)findViewObject("TbFuncionarioView2");
    }

    /**
     * Container's getter for ExisteCpfOuCnjp1.
     * @return ExisteCpfOuCnjp1
     */
    public ViewObjectImpl getExisteCpfOuCnjp1() {
        return (ViewObjectImpl)findViewObject("ExisteCpfOuCnjp1");
    }

    /**
     * Container's getter for TbVeiculoView1.
     * @return TbVeiculoView1
     */
    public ViewObjectImpl getTbVeiculoView1() {
        return (ViewObjectImpl)findViewObject("TbVeiculoView1");
    }

    /**
     * Container's getter for TbOrdemDeServicoView5.
     * @return TbOrdemDeServicoView5
     */
    public ViewObjectImpl getTbOrdemDeServicoView5() {
        return (ViewObjectImpl)findViewObject("TbOrdemDeServicoView5");
    }

    /**
     * Container's getter for ExistePlaca1.
     * @return ExistePlaca1
     */
    public ViewObjectImpl getExistePlaca1() {
        return (ViewObjectImpl)findViewObject("ExistePlaca1");
    }

    /**
     * Container's getter for VeiculoMMView1.
     * @return VeiculoMMView1
     */
    public ViewObjectImpl getVeiculoMMView1() {
        return (ViewObjectImpl)findViewObject("VeiculoMMView1");
    }

    /**
     * Container's getter for ListarMarcaView1.
     * @return ListarMarcaView1
     */
    public ViewObjectImpl getListarMarcaView1() {
        return (ViewObjectImpl)findViewObject("ListarMarcaView1");
    }

    /**
     * Container's getter for ListarModeloView1.
     * @return ListarModeloView1
     */
    public ViewObjectImpl getListarModeloView1() {
        return (ViewObjectImpl)findViewObject("ListarModeloView1");
    }

    /**
     * Container's getter for MotoristaCategoriaView1.
     * @return MotoristaCategoriaView1
     */
    public ViewObjectImpl getMotoristaCategoriaView1() {
        return (ViewObjectImpl)findViewObject("MotoristaCategoriaView1");
    }

    /**
     * Container's getter for ExisteCpfTbMot1.
     * @return ExisteCpfTbMot1
     */
    public ViewObjectImpl getExisteCpfTbMot1() {
        return (ViewObjectImpl)findViewObject("ExisteCpfTbMot1");
    }

    /**
     * Container's getter for ExisteCpfTbFuncionario1.
     * @return ExisteCpfTbFuncionario1
     */
    public ViewObjectImpl getExisteCpfTbFuncionario1() {
        return (ViewObjectImpl)findViewObject("ExisteCpfTbFuncionario1");
    }

    /**
     * Container's getter for FkFranquia1Link1.
     * @return FkFranquia1Link1
     */
    public ViewLinkImpl getFkFranquia1Link1() {
        return (ViewLinkImpl)findViewLink("FkFranquia1Link1");
    }

    /**
     * Container's getter for FkCatHab1Link1.
     * @return FkCatHab1Link1
     */
    public ViewLinkImpl getFkCatHab1Link1() {
        return (ViewLinkImpl)findViewLink("FkCatHab1Link1");
    }

    /**
     * Container's getter for FkOrdemDeServico1Link1.
     * @return FkOrdemDeServico1Link1
     */
    public ViewLinkImpl getFkOrdemDeServico1Link1() {
        return (ViewLinkImpl)findViewLink("FkOrdemDeServico1Link1");
    }

    /**
     * Container's getter for FkCliente1Link1.
     * @return FkCliente1Link1
     */
    public ViewLinkImpl getFkCliente1Link1() {
        return (ViewLinkImpl)findViewLink("FkCliente1Link1");
    }

    /**
     * Container's getter for FkFuncionario1Link1.
     * @return FkFuncionario1Link1
     */
    public ViewLinkImpl getFkFuncionario1Link1() {
        return (ViewLinkImpl)findViewLink("FkFuncionario1Link1");
    }

    /**
     * Container's getter for FkMotorista1Link1.
     * @return FkMotorista1Link1
     */
    public ViewLinkImpl getFkMotorista1Link1() {
        return (ViewLinkImpl)findViewLink("FkMotorista1Link1");
    }

    /**
     * Container's getter for TbFuncionarioTbPerfilFkLink1.
     * @return TbFuncionarioTbPerfilFkLink1
     */
    public ViewLinkImpl getTbFuncionarioTbPerfilFkLink1() {
        return (ViewLinkImpl)findViewLink("TbFuncionarioTbPerfilFkLink1");
    }

    /**
     * Container's getter for FkVeiculo1Link1.
     * @return FkVeiculo1Link1
     */
    public ViewLinkImpl getFkVeiculo1Link1() {
        return (ViewLinkImpl)findViewLink("FkVeiculo1Link1");
    }

    public int autenticarUsuario(String userid, String pass) {
        System.out.println("***************User = " + userid);
        System.out.println("***************Pass = " + pass);
        TbFuncionarioViewImpl myView =
            (TbFuncionarioViewImpl)getTbFuncionarioView1();
        myView.setWhereClause(" EMAIL = '" + userid + "' AND SENHA = '" +
                              pass + "'");
        System.out.println("***********Clause where = " +
                           myView.getWhereClause());
        myView.executeQuery();
        if (myView.getRowCount() == 0) {
            return 0;
        } else {
            return 1;
        }
    }

    /**
     * Container's getter for OsDadosView1.
     * @return OsDadosView1
     */
    public ViewObjectImpl getOsDadosView1() {
        return (ViewObjectImpl)findViewObject("OsDadosView1");
    }

    /**
     * Container's getter for DadosOS1.
     * @return DadosOS1
     */
    public ViewObjectImpl getDadosOS1() {
        return (ViewObjectImpl)findViewObject("DadosOS1");
    }
}
